#!/usr/bin/python

import httplib, urllib, csv, urllib2, socket, os, time, json, datetime, requests, ConfigParser, sys, traceback, subprocess

def	my_int(sth):
	if (sth == None or sth.isdigit() == False):
		return 0
	return int(sth)

class LogsType:
	ERROR = "ERR"
	WARNING = "WRG"

def singleton(cls):
	instance=cls()
	cls.__new__ = cls.__call__= lambda cls: instance
	cls.__init__ = lambda self: None
	return instance

@singleton
class Config():
	def get(self, section, item):
		return self.cp.get(section, item)
	
	def getInt(self, section, item):
		return self.cp.getint(section, item)

	def getBoolean(self, section, item):
		return self.cp.getboolean(section, item)

	def __init__(self):
		self.cp = ConfigParser.RawConfigParser()
		self.cp.read('/etc/newrelic/newrelic-agent.cfg')

class Agent:
	def update_postdata(self):
		self.post_data['components'] = []
		for component in self.components:
			self.post_data['components'].append(self.components[component])

	def log(self, errtype, message):
		self.logs_file.write("[" + errtype + "]" + ' ' + str(datetime.datetime.now()) + ' : ' + message +'\n')

	def populateMetrics(self, metrics, value_type, scale, value):
		label = "Component/" + value_type + "[" + scale + "]"
		if (value == 'Y'):
			value = 1
		if (value == None or value == ''):
			value = 0
		if label in metrics:
			yet = metrics[label]
			if type(yet) is dict:
				yet['min'] = (yet['min'] < value and yet['min'] or value)
				yet['max'] = (yet['max'] > value and yet['max'] or value)
				yet['total'] += value
				yet['count'] += 1
				yet['sum_of_squares'] += (value * value)
				metrics[label] = yet
			else:
				metrics[label] = {}
				metrics[label]['min'] = (yet < value and yet or value)
				metrics[label]['max'] = (yet > value and yet or value)
				metrics[label]['total'] = yet + value
				metrics[label]['count'] = 2
				metrics[label]['sum_of_squares'] = (yet * yet + value * value)
		else:
			metrics[label] = value

	def populateDeltaMetrics(self, name, metrics, value_type, scale, value):
		label = "Component/" + value_type + "[" + scale + "]"
		if (name not in self.old):
			self.old[name] = {}
		if (value == None or value == ''):
			value = 0
		delta = 0
		if label in self.old[name] and value > self.old[name][label]:
			delta = value - self.old[name][label]
		self.old[name][label] = value
		self.populateMetrics(metrics, value_type, scale, delta)
	
	def get_nfsstat_data(self):
                proc = subprocess.Popen(["nfsstat -ls4"], stdout=subprocess.PIPE, shell=True)
                (out, err) = proc.communicate()
                ret = {}
                for line in out.split('\n'):
                        content = line.split()
                        if (len(content) == 5):
                                ret[content[3].replace(':', '')] = my_int(content[4])
                return ret

	def post_datas(self):
		post_json = json.dumps(self.post_data, sort_keys=True, indent=4)
		print post_json
		headers = {"Content-Type": "application/json",
					"Accept": "application/json","X-License-Key": self.newrelic_license}

		conn = httplib.HTTPSConnection(self.platform_api_ip, timeout=5)
		conn.request("POST", self.platform_api_url, post_json, headers)
		response = conn.getresponse()
		return (response.status)

	def get_component_from_csv(self, row):
		duration = int(time.time() - self.last_poll_time)
                if (self.agent_host not in self.components):
                        tmp_component = {}
                        tmp_component['name'] = self.agent_host
                        tmp_component['guid'] = self.guid
                        tmp_component['duration'] = duration
                        self.components[self.agent_host] = tmp_component
                        metrics = {}
                else:
                        metrics = self.components[self.agent_host]['metrics']
                self.components[self.agent_host]['duration'] = duration
		reads=0
		writes=0
		if 'write' in row:
                	self.populateDeltaMetrics(self.agent_host, metrics, "Files/write", "Operations", row['write'])
                        writes += row['write']
                if 'read' in row:
                	self.populateDeltaMetrics(self.agent_host, metrics, "Files/read", "Operations", row['read'])
 			reads += row['read']
		if 'remove' in row:
              		self.populateDeltaMetrics(self.agent_host, metrics, "Files/remove", "Operations", row['remove'])
  			writes += row['remove']
		if 'readdir' in row:
	                self.populateDeltaMetrics(self.agent_host, metrics, "Directories/readdir", "Operations", row['readdir'])
                        reads += row['readdir']
                if 'rename' in row:
	                self.populateDeltaMetrics(self.agent_host, metrics, "Directories/rename", "Operations", row['rename'])
                        writes += row['rename']
		if 'create' in row:
	                self.populateDeltaMetrics(self.agent_host, metrics, "Directories/create", "Operations", row['create'])
 		        writes += row['create'] 	

                if 'readlink' in row:
			self.populateDeltaMetrics(self.agent_host, metrics, "FilesInformations/readlink", "Operations", row['readlink'])
                        reads += row['readlink']
		if 'access' in row:
	                self.populateDeltaMetrics(self.agent_host, metrics, "FilesInformations/access", "Operations", row['access'])
			reads += row['access']
		if 'getattr' in row:
	                self.populateDeltaMetrics(self.agent_host, metrics, "FilesInformations/getattr", "Operations", row['getattr'])
                        reads += row['getattr']
		if 'setattr' in row:
                	self.populateDeltaMetrics(self.agent_host, metrics, "FilesInformations/setattr", "Operations", row['setattr'])
			writes += row['setattr']
		if 'lookup' in row:
	                self.populateDeltaMetrics(self.agent_host, metrics, "FilesInformations/lookup", "Operations", row['lookup'])
			reads += row['lookup']
		if 'commit' in row:
	                self.populateDeltaMetrics(self.agent_host, metrics, "FilesInformations/commit", "Operations", row['commit'])
			writes += row['commit']
		if 'getfh' in row:
	                self.populateDeltaMetrics(self.agent_host, metrics, "FilesInformations/getfh", "Operations", row['getfh'])
			reads += row['getfh']
		if 'open' in row:
	                self.populateDeltaMetrics(self.agent_host, metrics, "FilesInformations/open", "Operations", row['open'])
			reads += row['open']
		if 'putfh' in row:
	                self.populateDeltaMetrics(self.agent_host, metrics, "FilesInformations/putfh", "Operations", row['putfh'])
			writes += row['putfh']
		if 'putrootfh' in row:
			self.populateDeltaMetrics(self.agent_host, metrics, "FilesInformations/putrootfh", "Operations", row['putrootfh'])
			writes += row['putrootfh']
		if 'renew' in row:
			self.populateDeltaMetrics(self.agent_host, metrics, "FilesInformations/renew", "Operations", row['renew'])
			writes += row['renew']
		if 'close' in row:
			self.populateDeltaMetrics(self.agent_host, metrics, "FilesInformations/close", "Operations", row['close'])
			writes += row['close']

                if 'total' in row:
			self.populateDeltaMetrics(self.agent_host, metrics, "Main/Total", "Operations", row['total'])
                self.populateDeltaMetrics(self.agent_host, metrics, "Main/Read", "Operations", reads)
                self.populateDeltaMetrics(self.agent_host, metrics, "Main/Write", "Operations", writes)

                
                self.components[self.agent_host]['metrics'] = metrics

	def run(self):
		run = True
		code = 200
		while (run):
			try:
				data = self.get_nfsstat_data()
				self.get_component_from_csv(data)
				self.update_postdata()
				code = self.post_datas()
				if (code == 200):
					# Clearing component cash
					self.components = {}
					self.last_poll_time = time.time()
				elif (code == 400):
					self.log(LogsType.ERROR, " 400 error encontered, request uncorrect")
					run = False
				elif (code == 403):
					self.log(LogsType.ERROR, " 403 acces forbidden, checkout your license key")
					run = False
				elif (code == 404):
					self.log(LogsType.ERROR, " 404 bad URL - checkout with developper of this application")
					run = False
				elif (code == 415):
					self.log(LogsType.ERROR, " 415 request incorrect")
					run = False
			except Exception as e:
				traceback.print_exc(file=sys.stdout)
				self.log(LogsType.ERROR, str(e))
				code = "THROWN"
			if (run):
				time.sleep( int(self.poll_cycle))
				
	def __init__(self):
		# Init NewRelic Variables
		self.platform_api_uri = Config().get('NewRelicAPI', 'uri')
		self.platform_api_url = Config().get('NewRelicAPI', 'url')
		self.platform_api_ip = Config().get('NewRelicAPI', 'ip')
		self.newrelic_license = Config().get('NewRelicAPI', 'license_key')
		self.poll_cycle = Config().getInt('NewRelicAPI', 'poll_cycle')

		# Init of agent informations
		self.guid = Config().get('Agent', 'nfs_v4_guid')
		self.agent_host = socket.gethostname()
		self.agent_pid = os.getpid()
		self.version = Config().get('Agent', 'version')
		self.agent_hash = {'host' : self.agent_host, 'pid' : self.agent_pid, 'version' : str(self.version)}

		# Init old dict for delta computing values
		self.old = {}
		
		# Init time of program start
		self.last_poll_time = time.time() - float(self.poll_cycle)

		# Init of component
		self.components = {}

		# Init post_datas
		self.post_data = {'agent': self.agent_hash, 'components':[]}

		# Init Logs
		self.logs_enabled = Config().getBoolean('Logs', 'enable')
		if (self.logs_enabled):
			self.logs_file = open(Config().get('Logs', 'file'), 'a')
			if (self.logs_file == None):
				sys.stderr.write('Impossible to open log_file, no logs saved')
				self.logs_enabled  = False

if __name__ == '__main__':
	euid = os.geteuid()
	if euid != 0:
		print ('This agent needs to be run as sudoers or root')
	else:
		p = Agent()
		p.run()

